# Use official Node.js LTS image
FROM node:20-alpine

# Set working directory
WORKDIR /app


# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy source files
COPY . .

# Expose port (change if your app uses a different port)
EXPOSE 3000

# Start the service
CMD ["node", "./dist/index.js"]