# Use official Node.js LTS image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy source files
COPY . .


# Expose port (match your app’s port)
EXPOSE 3003


# Make wait script executable
RUN chmod +x ./wait-for-rabbitmq.sh

CMD ["sh", "-c", "./wait-for-rabbitmq.sh rabbitmq 5672 node dist/index.js"]
